name: custom_drag_target
description: Flet CustomDragTarget control
repository: https://github.com/MyGithubAccount/custom-drag-target/src/flutter/custom_drag_target
version: 0.1.0
homepage: https://github.com/MyGithubAccount/custom-drag-target

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.28.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
